# Generated by Django 4.2.7 on 2023-11-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_automovile_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovile',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automoviles', to='personas.fabricante'),
        ),
    ]
