# Generated by Django 4.2.7 on 2023-11-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_automovile_fabricante'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovile',
            name='fecha_compra',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
